version: '3.8'
name: personalblog_database

services:
  db:
    image: postgres:15.4
    container_name: personalblog
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: personalblog
    ports:
      - "5432:5432"
    volumes:
      - personalblog_data:/var/lib/postgresql/data

volumes:
  personalblog_data: