name: personalblog_backend

services:
  api:
    image: gabrielluciano/personalblog-api:latest
    restart: on-failure
    depends_on:
      - database
    networks:
      - personalblog
    environment:
      API_SECRET: "${PB_API_SECRET}"
      IMAGE_SERVICE_URL: "${PB_IMAGE_SERVICE_URL}"
      SPRING_DATASOURCE_URL: "${PB_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${PB_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${PB_DB_PASSWORD}"
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: "600MB"

  database:
    image: postgres:15.4
    restart: on-failure
    networks:
      - personalblog
    environment:
      POSTGRES_DB: "${PB_DB_NAME}"
      POSTGRES_USER: "${PB_DB_USER}"
      POSTGRES_PASSWORD: "${PB_DB_PASSWORD}"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - personalblog_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "300MB"

  proxy:
    image: nginx:1.25.2
    restart: on-failure
    depends_on:
      - api
    networks:
      - personalblog
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "100MB"

volumes:
  personalblog_data:

networks:
  personalblog:
    name: personalblog_network
    driver: bridge
