version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: personalblog
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
    volumes:
      - personalblog_data:/var/lib/postgresql/data

volumes:
  personalblog_data: