name: personalblog_backend

services:
  api:
    image: gabrielluciano/personalblog-api
    build: .
    restart: on-failure
    depends_on:
      - postgres
    environment:
      API_SECRET: "${PB_API_SECRET}"
      SPRING_DATASOURCE_URL: "${PB_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${PB_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${PB_DB_PASSWORD}"
    deploy:
      resources:
        limits:
          memory: '0.25GB'
          cpus: '0.3'

  database:
    image: postgres:15.4
    environment:
      POSTGRES_DB: "${PB_DB_NAME}"
      POSTGRES_USER: "${PB_DB_USER}"
      POSTGRES_PASSWORD: "${PB_DB_PASSWORD}"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - personalblog_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    deploy:
      resources:
        limits:
          memory: '0.25GB'
          cpus: '0.3'

  proxy:
    image: nginx:1.25.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    deploy:
      resources:
        limits:
          memory: '0.07GB'
          cpus: '0.1'

volumes:
  personalblog_data:
