version: "3.8"
name: personalblog_backend

services:
  spring:
    image: personalblog
    container_name: personalblog_spring
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      API_SECRET: "${PB_API_SECRET}"
      SPRING_DATASOURCE_URL: "${PB_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${PB_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${PB_DB_PASSWORD}"
