spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  error:
    include-stacktrace: never
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: INFO

image:
  service:
    url: ${IMAGE_SERVICE_URL}
