spring:
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/personalblog
    username: postgres
    password: postgrespw

server:
  error:
    include-stacktrace: never
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

api:
  secret: secret