spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none

server:
  error:
    include-stacktrace: never
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: INFO
