spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/dbname
    username: dbusername
    password: dbpassword

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

api:
  secret: secret
