name: Personal Blog Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: npm
        cache-dependency-path: './frontend/package-lock.json'
    - name: Run tests
      run: cd ./frontend && npm ci && npm test