name: Personal Blog Angular CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: npm
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Check lint rules
        run: npm run lint
      - name: Check coding formatting rules
        run: npx prettier --check .
      - name: Run tests
        run: npm test
