name: Personal Blog Backend Test CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  API_SECRET: secret
  APP_FOLDER: backend

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run unit tests
        working-directory: ${{ env.APP_FOLDER }}
        run: mvn -B test

      - name: Run integration tests
        working-directory: ${{ env.APP_FOLDER }}
        run: mvn test -B -P integration-tests
