name: Personal Blog Backend Test and Deploy CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - "aws/**"
      - "appspec.yml"
      
env:
  API_SECRET: secret
  APP_FOLDER: backend
  AWS_REGION: us-east-2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: Github-Action-Role

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run unit tests
        working-directory: ${{ env.APP_FOLDER }}
        run: mvn -B test

      - name: Run integration tests
        working-directory: ${{ env.APP_FOLDER }}
        run: mvn test -B -P integration-tests

      - name: Build and Package
        working-directory: ${{ env.APP_FOLDER }}
        run: mvn clean package -DskipTests

      - name: Upload Artifact to s3
        working-directory: ${{ env.APP_FOLDER }}
        run: |
          aws s3 cp target/*.jar s3://${{ secrets.PROD_S3_BUCKET }}/app.jar
          aws s3 cp Dockerfile s3://${{ secrets.PROD_S3_BUCKET }}/
          aws s3 cp docker-compose.yml s3://${{ secrets.PROD_S3_BUCKET }}/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: Github-Action-Role
      - run: |
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment --application-name PersonalBlog --deployment-group-name PersonalBlogDeployGroup --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
