name: Personal Blog Frontend Test CI

on:
  pull_request:
    branches: ["main"]

env:
  APP_FOLDER: frontend

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.APP_FOLDER }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: npm
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Check lint rules
        run: npm run lint
      - name: Check coding formatting rules
        run: npx prettier --check .
      - name: Run tests
        run: npm test
