name: Personal Blog Maven CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  API_SECRET: secret

jobs:
  backend-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run unit tests
      run: cd ./backend && mvn -B test
    - name: Run integration tests
      run: cd ./backend && mvn test -B -P integration-tests
